"""Add picture column to Player model

Revision ID: 6895dc14f04d
Revises: 
Create Date: 2024-07-19 15:37:21.077895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6895dc14f04d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_player_association')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('picture')

    op.create_table('coach_player_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coach_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
